spring.application.name=backend
# Server
server.port=8080

# Cricket API
cricket.api.key=65d52fdba4msh1ebf77b769b11efp15acbajsn62fa512fbdee
cricket.api.host=free-cricbuzz-cricket-api.p.rapidapi.com

# Football API
football.api.key=65d52fdba4msh1ebf77b769b11efp15acbajsn62fa512fbdee
football.api.host=free-api-live-football-data.p.rapidapi.com

# Cache
spring.cache.type=simple