spring.application.name=backend
# Server
server.port=8080

# Cricket API
cricbuzz.unofficial.key=65d52fdba4msh1ebf77b769b11efp15acbajsn62fa512fbdee
cricbuzz.unofficial.host=unofficial-cricbuzz.p.rapidapi.com
# Football API
football.api.key=65d52fdba4msh1ebf77b769b11efp15acbajsn62fa512fbdee
football.api.host=free-api-live-football-data.p.rapidapi.com

# Cache
spring.cache.type=simple